### PR TITLE
Fleet Adapter API hooks for direct task submission and robot interruption

### PR DESCRIPTION
**Pull request by mxgrey**
This PR adds new Fleet Adapter API features to allow system integrators to implement custom ways to issue direct task requests to their fleets as well as interrupt their robots, overriding any current (or upcoming) tasks and any emergency pullover behavior.

This PR depends on two others:
* https://github.com/open-rmf/rmf_internal_msgs/pull/36
* https://github.com/open-rmf/rmf_task/pull/58

### CODE REVIEW

**Review by cnboonhan — COMMENTED** [review]
Generally seems to work according to spec: Unfortunately I don't know enough to comment on code itself, but the API seems solid. 

I noticed this validation error on the RMF stdout, which doesn't break any functionality:
```
[full_control-12] [ERROR] [1646023568.423580098] [tinyRobot_fleet_adapter]: Failed to validate message [{"data":{"active":1,"assigned_to
":{"group":"tinyRobot","name":"tinyRobot2"},"booking":{"id":"patrol.dispatch-0","unix_millis_earliest_start_time":29113},"category":"Pat
rol","completed":[],"detail":"","estimate_millis":531100,"interruptions":{"0":{"labels":[],"resumed_by":{"labels":[],"unix_millis_resume
_time":56783},"unix_millis_request_time":36589},"1":{"labels":["emergency pullover"],"resumed_by":{"labels":["emergency finished"],"unix
_millis_resume_time":120021},"unix_millis_request_time":74763},"2":{"labels":[],"resumed_by":{"labels":[],"unix_millis_resume_time":1270
15},"unix_millis_request_time":104222},"3":{"labels":["emergency pullover"],"unix_millis_request_time":139302},"4":{"labels":[],"resumed
_by":{"labels":[],"unix_millis_resume_time":178015},"unix_millis_request_time":141701},"5":{"labels":[],"unix_millis_request_time":19009
4}},"original_estimate_millis":505385,"pending":[2,3,4,5,6,7,8,9,10],"phases":{"1":{"category":"Go to [place:pantry]","detail":"Moving t
he robot from [place:tinyRobot2_charger] to [place:pantry]","estimate_millis":25715,"events":{"0":{"deps":[],"detail":"Moving the robot
from [place:tinyRobot2_charger] to [place:pantry]","id":0,"name":"Go to [place:pantry]","status":"standby"},"1":{"deps":[],"detail":"","
id":1,"name":"Move to [place:pantry]","status":"underway"},"2":{"deps":[],"detail":"","id":2,"name":"Move to [place:pantry]","status":"u
nderway"},"3":{"deps":[],"detail":"","id":3,"name":"Move to [place:pantry]","status":"underway"}},"final_event_id":0,"id":1,"original_es
timate_millis":27344,"unix_millis_start_time":31291},"10":{"category":"Go to [place:supplies]","detail":"Moving the robot from [place:pa
ntry] to [place:supplies]","estimate_millis":56426,"id":10},"2":{"category":"Go to [place:supplies]","detail":"Moving the robot from [pl
ace:pantry] to [place:supplies]","estimate_millis":56426,"id":2},"3":{"category":"Go to [place:pantry]","detail":"Moving the robot from
[place:supplies] to [place:pantry]","estimate_millis":55812,"id":3},"4":{"category":"Go to [place:supplies]","detail":"Moving the robot
from [place:pantry] to [place:supplies]","estimate_millis":56426,"id":4},"5":{"category":"Go to [place:pantry]","detail":"Moving the rob
ot from [place:supplies] to [place:pantry]","estimate_millis":55812,"id":5},"6":{"category":"Go to [place:supplies]","detail":"Moving th
e robot from [place:pantry] to [place:supplies]","estimate_millis":56426,"id":6},"7":{"category":"Go to [place:pantry]","detail":"Moving
 the robot from [place:supplies] to [place:pantry]","estimate_millis":55812,"id":7},"8":{"category":"Go to [place:supplies]","detail":"M
oving the robot from [place:pantry] to [place:supplies]","estimate_millis":56426,"id":8},"9":{"category":"Go to [place:pantry]","detail"
:"Moving the robot from [place:supplies] to [place:pantry]","estimate_millis":55812,"id":9}},"status":"standby","unix_millis_finish_time
":760879,"unix_millis_start_time":31291},"type":"task_state_update"}]: [At /data/interruptions of {"0":{"labels":[],"resumed_by":{"label
s":[],"unix_millis_resume_time":56783},"unix_millis_request_time":36589},"1":{"labels":["emergency pullover"],"resumed_by":{"labels":["e
mergency finished"],"unix_millis_resume_time":120021},"unix_millis_request_time":74763},"2":{"labels":[],"resumed_by":{"labels":[],"unix
_millis_resume_time":127015},"unix_millis_request_time":104222},"3":{"labels":["emergency pullover"],"unix_millis_request_time":139302},
"4":{"labels":[],"resumed_by":{"labels":[],"unix_millis_resume_time":178015},"unix_millis_request_time":141701},"5":{"labels":[],"unix_m
illis_request_time":190094}} - validation failed for additional property '0': required property 'token' not found in object
```

I also noticed that with the previous way of running teleoperation tasks, the second command to resume no longer works:
```
 ros2 run rmf_demos_tasks dispatch_teleop -F tinyRobot -R tinyRobot2 -s pantry --use_sim_time
 ros2 topic pub /action_execution_notice rmf_fleet_msgs/msg/ModeRequest '{fleet_name: tinyRobot, robot_name: tinyRobot2, mode: {mode: 8}}' --once
```
In the midst of recompiling RMF with main branch to test where this regression happened.

Also, I noticed that the `interrupt_robot` executable publishes messages on a timer, instead of a one-time message. Is this preferred?

**Comment by mxgrey** [comment]
> I noticed this validation error on the RMF stdout, which doesn't break any functionality:

Thanks for pointing that out! I forgot to open a PR for `rmf_api_msgs`: https://github.com/open-rmf/rmf_api_msgs/pull/21

We should definitely merge that first.

> Also, I noticed that the interrupt_robot executable publishes messages on a timer, instead of a one-time message. Is this preferred?

Yeah, DDS discovery is a bit non-deterministic, so the program just spams the message until the user decides to stop sending it. There's no negative impact of spamming the message because the implementation of interruption will just ignore the redundant ones, as long as they all share the same "id".

**Review by cnboonhan — APPROVED** [review]
I can't figure out how to get the previous way of "cancelling teleop commands"  for RMF operation to resume.
```
 ros2 topic pub /action_execution_notice rmf_fleet_msgs/msg/ModeRequest '{fleet_name: tinyRobot, robot_name: tinyRobot2, mode: {mode: 8}}' --once
```

In any case, sending a task cancellation request for the teleop works fine, so I think its ok to use task cancellation API instead. The previous method seemed like a hack anyway.

**Comment by mxgrey** [comment]
> I can't figure out how to get the previous way of "cancelling teleop commands" for RMF operation to resume.

I'm not sure what you're referring to here. Do you mean the old task cancellation ROS2 service which only worked for pending tasks? If so, that feature has been removed and replaced with the new JSON method.

**Comment by mxgrey** [comment]
> I can't figure out how to get the previous way of "cancelling teleop commands" for RMF operation to resume.

Could you elaborate on what you're referring to here?

**Comment by mxgrey** [comment]
Oh, that's not a good thing! We definitely need to maintain that kind of support for `perform_action`.

So in your testing, that teleoperation use case no longer works at all? Or it doesn't work as intended when the new task interruption feature is used on top of it?

**Comment by cnboonhan** [comment]
Neither

the following works as before. It sends a robot to a location specified by -s, and then stops RMF control until the task cancellation from rmf-web is called:
```
ros2 run rmf_demos_tasks dispatch_teleop -F tinyRobot -R tinyRobot2 -s pantry --use_sim_time
# followed by task cancellation request from rmf-web
```

This used to work I believe, but now doesn't:
```
ros2 run rmf_demos_tasks dispatch_teleop -F tinyRobot -R tinyRobot2 -s pantry --use_sim_time

ros2 topic pub /action_execution_notice rmf_fleet_msgs/msg/ModeRequest '{fleet_name: tinyRobot, robot_name: tinyRobot2, mode: {mode: 8}}' --once
```

But since the former works, I think we could just replace the `/action_execution_notice` with task cancellation called from command line?

**Comment by mxgrey** [comment]
> But since the former works, I think we could just replace the /action_execution_notice with task cancellation called from command line?

No, canceling a task is not the same as indicating that an action has finished performing. A task may involve multiple actions that need to be performed in a sequence. Canceling the task when one of those actions finishes means the rest of the actions won't get performed unless you create a whole new task for them.

> This used to work I believe, but now doesn't:

So you're saying that those commands no longer work at all? Even if you don't make use of the new task interruption features? If so, could you try running that test against the `main` branch, because it's extremely suspicious that the new feature would negatively impact behavior when the new feature isn't even being used.

**Comment by mxgrey** [comment]
Looking at the implementation of [`PerformAction`](https://github.com/open-rmf/rmf_ros2/blob/9b4b8a8cc38b323f875a55c70f307446584d1639/rmf_fleet_adapter/src/rmf_fleet_adapter/events/PerformAction.cpp#L211-L218) it looks like nothing in particular will happen with `PerformAction` when it gets interrupted, except that it will be re-executed once the task is told to resume.

Truth be told, this does seem like a flawed design. We should really provide some way for the action executor to know that the task has been interrupted and then tell it to resume later. But regardless, I can't think of any reason there would be interference between the new feature and the intended behavior :thinking:

**Comment by cnboonhan** [comment]
I am starting to think its probably not related to this PR, or i'm doing something careless. I did pull latest main and did a clean build, but same issue presents.

**Comment by mxgrey** [comment]
Looks like your message should have [`mode: 0`](https://github.com/open-rmf/rmf_internal_msgs/blob/7ed8ae5319ada774b9829eeb9e9b41d08e09c822/rmf_fleet_msgs/msg/RobotMode.msg#L2) instead of `mode: 8` because the fleet adapter is listening for [`MODE_IDLE`](https://github.com/open-rmf/rmf_ros2/blob/9b4b8a8cc38b323f875a55c70f307446584d1639/rmf_fleet_adapter/src/full_control/main.cpp#L972).

**Comment by cnboonhan** [comment]
I guess i'm really going blind >.< 

ok, false alarm! i think i looked at the video and read 8 instead of 0. It seemed to make sense on the ModeRequest definition as well

**Comment by mxgrey** [comment]
I've added the python bindings for the new API features. They can be tested out by running `scripts/test_interrupt.py` in `rmf_fleet_adapter_python`. It's not part of the unit tests at the moment because I forked it off of `test_loop.py` which is also not included in the unit tests. I'm not sure if there's a reason they're being excluded, but they can be moved into the unit tests together if a time comes for that in the future.

**Review by cnboonhan — COMMENTED** [review]
from my local tests with colcon `defaults.yaml`, i think the correct way to specify this is in fact "executor": "sequential". Specifying it this way, executor: ["sequential"], in fact, seem to do a parallel build. Should we remove this executor clause entirely, given that we now know that the issue was not due to OOM?

**Comment by mxgrey** [comment]
I think we may as well use the sequential processing, since that may very well become an issue in the future. I think the `MAKEFLAGS: j1` probably helped enough to get past this hiccup, but if we don't use sequential package building then we may end up back in this position in the future.

**Review by cnboonhan — DISMISSED** [review]
Works great! LGTMMM

**Review by cnboonhan — APPROVED** [review]
LGTM!

**Pull request merged**
