### PR TITLE
Populate TaskProfile in TaskSummary

### LINKED ISSUE #80: TaskProfile field in TaskSummary not populated
The current `TaskManager` does not populate the `TaskProfile` field in the `TaskSummary` message before publishing.

### PR DESCRIPTION
**Pull request by Yadunund**
Fix #80 by implementing select changes from #24

### CODE REVIEW

**Review by youliangtan — APPROVED** [review]
LGTM!! Also tested it, looks fine :+1:

**Comment by Yadunund** [comment]
Hmm not sure why `test_rmf_fleet_adapter` is failing after merging in `main` 🤔 
```
  The following tests FAILED:
  	  2 - test_rmf_fleet_adapter (Failed)
  Errors while running CTest
  Output from these tests are in: /home/runner/work/rmf_ros2/rmf_ros2/ros_ws/build/rmf_fleet_adapter/Testing/Temporary/LastTest.log
  Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
  ---
  ```

**Comment by mxgrey** [comment]
According to the test artifacts, a segfault happened in `test_RequestLift`. I don't see any particular explanation for that, and I haven't seen a crash happen there before. Let's keep a careful eye on that test moving forward, to see if it crashes regularly. For now, let's just rerun the test and not block this PR, since it's almost certainly an unrelated issue.

**Comment by Yadunund** [comment]
Re-ran the test and it seems to pass this time.

**Review by youliangtan — APPROVED** [review]
:tada:

**Pull request merged**
