### PR TITLE
Fixing CI.

### PR DESCRIPTION
**Pull request by orensbruli**
Multiple minor fixes were applied to CI files.
Signed-off-by: Esteban Martinena <orensbruli@gmail.com>

### CODE REVIEW

**Review by ahcorde — CHANGES_REQUESTED** [review]
CI is still using `focal`

**Comment by orensbruli** [comment]
> CI is still using `focal`

Do you mean the `asan` check?

**Review by ahcorde — CHANGES_REQUESTED** [review]
This job is failing `github pages / deploy (pull_request)`

**Comment by orensbruli** [comment]
> This job is failing `github pages / deploy (pull_request)`

Yes, I mentioned this in my previous comment. I moved to a different issue and PR 
> gh_pages is still failing and needs some attention (https://github.com/open-rmf/rmf/issues/285#ghpages) but I think we can go with a different issue and PR for that one. Just created: https://github.com/open-rmf/rmf_ros2/issues/254

Also, it looks like it has never been used, so we probably should remove that workflow and not spend time fixing it.

**Review by ahcorde — APPROVED** [review]

**Pull request merged**
