### PR TITLE
Fix removal of duplicate schemas

### PR DESCRIPTION
**Pull request by omarmhamza**
### Bug fix / Enhancement 

This PR contains removal of duplicate schema entries.

### CODE REVIEW

**Comment by Yadunund** [comment]
Thanks for the contribution. The changes are ok but could you ensure our DCO check passes by following the guidelines [here](https://github.com/open-rmf/rmf_ros2/pull/290/checks?check_run_id=15363839219)

**Comment by omarmhamza** [comment]
Hello @Yadunund I made the appropriate changes for the DCO, I believe its ready to be merged. Thank you!

**Review by Yadunund — APPROVED** [review]

**Review by Yadunund — CHANGES_REQUESTED** [review]
Oh sorry just noticed that his PR is targeting `humble`. Could you re-target `main`?  That's where all new features and fixes should go in. We will backport changes to distro branches if necessary.

Edit: It might be easier to open a new PR if the merge conflicts are challenging to resolve.

**Comment by omarmhamza** [comment]
Got it. No worries, I made the necessary changes, it should now merge to `main` without conflicts.

**Comment by Yadunund** [comment]
Looks like DCO is failing now 😅

**Comment by omarmhamza** [comment]
hehe it seems that an older commit sha: 48e78cb, is causing that. Anyways I will create a fresh PR from a new branch: #294

**Pull request closed without merging**
